node {
    try {
        stage("build") {
            println("looking good so far...")
        }
        stage('test') {
            println("test has failed.")
            sh 'exit 1'
        }
    } catch (e) {
        currentBuild.result = "FAILURE";
        slackSend(color: "#FF0000", message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")

        throw e;
    }

}